### PR TITLE
HUBDEV-1882 removing hardcoded tel3A

### PR DESCRIPTION
**Pull request by Rajithkonara**
JIRA Issue Link : (https://jira.wso2telco.com/jira/browse/HUBDEV-1882)

### Summary of Changes
removing hardcoded tel3A+

### CODE REVIEW

**Comment by tharinduwso2telco** [comment]
retest this please

**Comment by tharinduwso2telco** [comment]
retest this please

**Comment by Rajithkonara** [comment]
retest this please

**Comment by Nuwan-Walisundara** [comment]
build failed

**Comment by tharinduwso2telco** [comment]
retest this please

**Pull request closed without merging**
